config/routes.rb
Flick::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions

  resources :pixes


  resources :albums


  root :to => 'albums#index'
end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :pix
  belongs_to :user
end

app/models/pix.rb
class Pix < ActiveRecord::Base
  attr_accessible :category, :description, :image, :name
  mount_uploader :image, ImgUploader
  belongs_to :Album
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  attr_accessible :email, :password, :password_confirmation
  has_many :albums
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(params[:album])

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pixes_controller.rb
class PixesController < ApplicationController
  # GET /pixes
  # GET /pixes.json
  def index
    @pixes = Pix.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pixes }
    end
  end

  # GET /pixes/1
  # GET /pixes/1.json
  def show
    @pix = Pix.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pix }
    end
  end

  # GET /pixes/new
  # GET /pixes/new.json
  def new
    @pix = Pix.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pix }
    end
  end

  # GET /pixes/1/edit
  def edit
    @pix = Pix.find(params[:id])
  end

  # POST /pixes
  # POST /pixes.json
  def create
    @pix = Pix.new(params[:pix])

    respond_to do |format|
      if @pix.save
        format.html { redirect_to @pix, notice: 'Pix was successfully created.' }
        format.json { render json: @pix, status: :created, location: @pix }
      else
        format.html { render action: "new" }
        format.json { render json: @pix.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pixes/1
  # PUT /pixes/1.json
  def update
    @pix = Pix.find(params[:id])

    respond_to do |format|
      if @pix.update_attributes(params[:pix])
        format.html { redirect_to @pix, notice: 'Pix was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pix.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pixes/1
  # DELETE /pixes/1.json
  def destroy
    @pix = Pix.find(params[:id])
    @pix.destroy

    respond_to do |format|
      format.html { redirect_to pixes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = login(params[:email], params[:password], params[:remember_me])
    if user
      redirect_back_or_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Email or password was invalid"
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render :new
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pixes_helper.rb
module PixesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>Listing albums</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @albums.each do |album| %>
  <tr>
    <td><%= album.name %></td>
    <td><%= album.description %></td>
    <td><%= link_to 'Show', album %></td>
    <td><%= link_to 'Edit', edit_album_path(album) %></td>
    <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @album.name %>
</p>

<p>
  <b>Description:</b>
  <%= @album.description %>
</p>


<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flick</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log out", logout_path %>
  <% else %>
    <%= link_to "Sign up", signup_path %> or
    <%= link_to "log in", login_path %>.
  <% end %>

<%= yield %>

</body>
</html>

app/views/pixes/_form.html.erb
<%= form_for(@pix, :html_options => {:multipart => true}) do |f| %>

  <% if @pix.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pix.errors.count, "error") %> prohibited this pix from being saved:</h2>

      <ul>
      <% @pix.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pixes/edit.html.erb
<h1>Editing pix</h1>

<%= render 'form' %>

<%= link_to 'Show', @pix %> |
<%= link_to 'Back', pixes_path %>

app/views/pixes/index.html.erb
<h1>Listing pixes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th>Image</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pixes.each do |pix| %>
  <tr>
    <td><%= pix.name %></td>
    <td><%= pix.category %></td>
    <td><%= pix.image %></td>
    <td><%= pix.description %></td>
    <td><%= link_to 'Show', pix %></td>
    <td><%= link_to 'Edit', edit_pix_path(pix) %></td>
    <td><%= link_to 'Destroy', pix, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pix', new_pix_path %>

app/views/pixes/new.html.erb
<h1>New pix</h1>

<%= render 'form' %>

<%= link_to 'Back', pixes_path %>

app/views/pixes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @pix.name %>
</p>

<p>
  <b>Category:</b>
  <%= @pix.category %>
</p>

<p>
  <%= image_tag @pix.image %>
</p>

<p>
  <b>Description:</b>
  <%= @pix.description %>
</p>


<%= link_to 'Edit', edit_pix_path(@pix) %> |
<%= link_to 'Back', pixes_path %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>